# Generated by Django 3.2.6 on 2021-08-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_url', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('json_concept', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'concept',
            },
        ),
        migrations.CreateModel(
            name='NameSpace',
            fields=[
                ('ns_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'name_space',
            },
        ),
        migrations.CreateModel(
            name='SemanticArea',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'semantic_area',
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'use_case',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('profile', models.TextField()),
                ('ns_id', models.ForeignKey(db_column='ns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.namespace')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('report_json', models.JSONField()),
                ('institute', models.TextField()),
                ('language', models.TextField()),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.usecase')),
            ],
            options={
                'db_table': 'report',
                'unique_together': {('id_report', 'language')},
            },
        ),
        migrations.CreateModel(
            name='AnnotationLabel',
            fields=[
                ('seq_number', models.IntegerField()),
                ('label', models.TextField(primary_key=True, serialize=False)),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.usecase')),
            ],
            options={
                'db_table': 'annotation_label',
                'unique_together': {('label', 'seq_number')},
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('mention_text', models.TextField(blank=True, null=True)),
                ('start', models.IntegerField(primary_key=True, serialize=False)),
                ('stop', models.IntegerField()),
                ('language', models.TextField()),
                ('id_report', models.ForeignKey(db_column='id_report', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.report')),
            ],
            options={
                'db_table': 'mention',
                'unique_together': {('start', 'stop', 'id_report', 'language')},
            },
        ),
        migrations.CreateModel(
            name='GroundTruthLogFile',
            fields=[
                ('insertion_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('language', models.TextField()),
                ('gt_type', models.TextField()),
                ('gt_json', models.JSONField()),
                ('id_report', models.ForeignKey(db_column='id_report', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.report')),
                ('ns_id', models.ForeignKey(db_column='ns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.namespace')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.user')),
            ],
            options={
                'db_table': 'ground_truth_log_file',
                'unique_together': {('insertion_time', 'id_report', 'language', 'username', 'ns_id')},
            },
        ),
        migrations.CreateModel(
            name='Linked',
            fields=[
                ('start', models.OneToOneField(db_column='start', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MedTAG_sket_dock_App.mention')),
                ('stop', models.IntegerField()),
                ('language', models.TextField()),
                ('insertion_time', models.DateTimeField(blank=True, null=True)),
                ('concept_url', models.ForeignKey(db_column='concept_url', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.concept')),
                ('id_report', models.ForeignKey(db_column='id_report', on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='MedTAG_sket_dock_App.report')),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.semanticarea')),
                ('ns_id', models.ForeignKey(db_column='ns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.namespace')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.user')),
            ],
            options={
                'db_table': 'linked',
                'unique_together': {('name', 'username', 'ns_id', 'concept_url', 'start', 'stop', 'id_report', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('insertion_time', models.DateTimeField(blank=True, null=True)),
                ('concept_url', models.OneToOneField(db_column='concept_url', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MedTAG_sket_dock_App.concept')),
                ('language', models.TextField()),
                ('id_report', models.ForeignKey(db_column='id_report', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.report')),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.semanticarea')),
                ('ns_id', models.ForeignKey(db_column='ns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.namespace')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.user')),
            ],
            options={
                'db_table': 'contains',
                'unique_together': {('concept_url', 'id_report', 'language', 'username', 'ns_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConceptHasUc',
            fields=[
                ('concept_url', models.OneToOneField(db_column='concept_url', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MedTAG_sket_dock_App.concept')),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.usecase')),
            ],
            options={
                'db_table': 'concept_has_uc',
                'unique_together': {('concept_url', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BelongTo',
            fields=[
                ('name', models.OneToOneField(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MedTAG_sket_dock_App.semanticarea')),
                ('concept_url', models.ForeignKey(db_column='concept_url', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.concept')),
            ],
            options={
                'db_table': 'belong_to',
                'unique_together': {('name', 'concept_url')},
            },
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id_report', models.OneToOneField(db_column='id_report', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MedTAG_sket_dock_App.report')),
                ('language', models.TextField()),
                ('seq_number', models.IntegerField()),
                ('insertion_time', models.DateTimeField(blank=True, null=True)),
                ('label', models.ForeignKey(db_column='label', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.annotationlabel')),
                ('ns_id', models.ForeignKey(db_column='ns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.namespace')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.user')),
            ],
            options={
                'db_table': 'associate',
                'unique_together': {('id_report', 'language', 'username', 'ns_id', 'seq_number', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Annotate',
            fields=[
                ('insertion_time', models.DateTimeField(blank=True, null=True)),
                ('start', models.OneToOneField(db_column='start', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MedTAG_sket_dock_App.mention')),
                ('stop', models.IntegerField()),
                ('language', models.TextField()),
                ('id_report', models.ForeignKey(db_column='id_report', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.report')),
                ('ns_id', models.ForeignKey(db_column='ns_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.namespace')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='MedTAG_sket_dock_App.user')),
            ],
            options={
                'db_table': 'annotate',
                'unique_together': {('username', 'ns_id', 'start', 'stop', 'id_report', 'language')},
            },
        ),
    ]
